services:
  api:
    build: .
    volumes:
      - ~/database:/app/database
    environment:
      - GLAURUNG_ACCESS_TOKEN_SECRET=${GLAURUNG_ACCESS_TOKEN_SECRET}
      - PROD=true
    ports:
      - "80:4000"
