service: glaurung
frameworkVersion: "3"

plugins:
  - serverless-lift

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x

# custom: ${file(./serverless/custom.yml)}

constructs:
  web:
    type: single-page-app
    path: ./dist
    # domain:
    #   - ${self:custom.global.domain.${self:provider.stage}}
    #   - www.${self:custom.global.domain.${self:provider.stage}}
    # certificate: ${self:custom.global.certificate.${self:provider.stage}}
